import { handSlot } from './hand';

export const verbalSlots = [
  handSlot({
    id: 'verbal.analogy-1',
    section: 'verbal',
    difficulty: 1,
    title: 'Analogy',
    timeLimit: 30,
    quick: true,
    items: [
      { prompt: 'Bird is to nest as bee is to ___.', choices: ['hive', 'honey', 'flower', 'wing', 'sting'], explanation: 'A bird lives in a nest; a bee lives in a hive.' },
      { prompt: 'Glove is to hand as sock is to ___.', choices: ['foot', 'shoe', 'knee', 'wool', 'leg'], explanation: 'A glove covers a hand; a sock covers a foot.' },
      { prompt: 'Hot is to cold as tall is to ___.', choices: ['short', 'high', 'warm', 'wide', 'big'], explanation: 'Hot and cold are opposites; the opposite of tall is short.' },
      { prompt: 'Pen is to write as knife is to ___.', choices: ['cut', 'fork', 'sharp', 'kitchen', 'steel'], explanation: 'A pen is used to write; a knife is used to cut.' },
      { prompt: 'Puppy is to dog as kitten is to ___.', choices: ['cat', 'mouse', 'cub', 'litter', 'fur'], explanation: 'A puppy is a young dog; a kitten is a young cat.' },
      { prompt: 'Day is to night as summer is to ___.', choices: ['winter', 'spring', 'sun', 'hot', 'autumn'], explanation: 'Day and night are opposite halves of a day; summer and winter are opposite seasons.' },
    ],
  }),
  handSlot({
    id: 'verbal.analogy-2',
    section: 'verbal',
    difficulty: 3,
    title: 'Analogy',
    timeLimit: 40,
    items: [
      { prompt: 'Author is to novel as composer is to ___.', choices: ['symphony', 'orchestra', 'piano', 'conductor', 'concert'], explanation: 'An author creates a novel; a composer creates a symphony.' },
      { prompt: 'Thermometer is to temperature as odometer is to ___.', choices: ['distance', 'speed', 'fuel', 'time', 'pressure'], explanation: 'A thermometer measures temperature; an odometer measures distance travelled. (Speed is measured by a speedometer.)' },
      { prompt: 'Drought is to water as famine is to ___.', choices: ['food', 'hunger', 'poverty', 'desert', 'disease'], explanation: 'A drought is a severe shortage of water; a famine is a severe shortage of food.' },
      { prompt: 'Sculptor is to chisel as surgeon is to ___.', choices: ['scalpel', 'hospital', 'patient', 'operation', 'doctor'], explanation: 'A chisel is the sculptor\'s cutting tool; a scalpel is the surgeon\'s.' },
      { prompt: 'Fish is to school as wolf is to ___.', choices: ['pack', 'den', 'herd', 'flock', 'howl'], explanation: 'A group of fish is a school; a group of wolves is a pack.' },
      { prompt: 'Petal is to flower as page is to ___.', choices: ['book', 'word', 'paper', 'tree', 'library'], explanation: 'A petal is one part of a flower; a page is one part of a book.' },
    ],
  }),
  handSlot({
    id: 'verbal.analogy-3',
    section: 'verbal',
    difficulty: 4,
    title: 'Analogy',
    timeLimit: 45,
    items: [
      { prompt: 'Ephemeral is to permanent as scarce is to ___.', choices: ['abundant', 'rare', 'valuable', 'temporary', 'empty'], explanation: 'Ephemeral is the opposite of permanent; scarce is the opposite of abundant.' },
      { prompt: 'Cartographer is to map as lexicographer is to ___.', choices: ['dictionary', 'language', 'novel', 'alphabet', 'grammar'], explanation: 'A cartographer compiles maps; a lexicographer compiles dictionaries.' },
      { prompt: 'Pride is to lions as murder is to ___.', choices: ['crows', 'wolves', 'owls', 'geese', 'killers'], explanation: 'A group of lions is a pride; a group of crows is a murder. (Owls form a parliament, geese a gaggle.)' },
      { prompt: 'Prologue is to epilogue as overture is to ___.', choices: ['finale', 'opera', 'intermission', 'aria', 'conductor'], explanation: 'A prologue opens a work and an epilogue closes it; an overture opens a musical work and a finale closes it.' },
      { prompt: 'Hammer is to anvil as pestle is to ___.', choices: ['mortar', 'grain', 'kitchen', 'mill', 'spice'], explanation: 'A hammer strikes against an anvil; a pestle grinds against a mortar.' },
      { prompt: 'Apiary is to bees as aviary is to ___.', choices: ['birds', 'apes', 'aircraft', 'fish', 'honey'], explanation: 'An apiary is where bees are kept; an aviary is where birds are kept.' },
    ],
  }),
  handSlot({
    id: 'verbal.odd-one-out',
    section: 'verbal',
    difficulty: 2,
    title: 'Odd one out',
    timeLimit: 30,
    quick: true,
    items: [
      { prompt: 'Which word does not belong with the others?', choices: ['Bronze', 'Copper', 'Iron', 'Silver', 'Zinc'], explanation: 'Bronze is an alloy. Copper, iron, silver and zinc are chemical elements.' },
      { prompt: 'Which word does not belong with the others?', choices: ['Shark', 'Whale', 'Dolphin', 'Seal', 'Walrus'], explanation: 'A shark is a fish. The others are mammals.' },
      { prompt: 'Which word does not belong with the others?', choices: ['Trumpet', 'Violin', 'Cello', 'Harp', 'Guitar'], explanation: 'A trumpet is a brass instrument. The others are string instruments.' },
      { prompt: 'Which word does not belong with the others?', choices: ['Triangle', 'Square', 'Rhombus', 'Rectangle', 'Trapezoid'], explanation: 'A triangle has three sides. The others are quadrilaterals with four.' },
      { prompt: 'Which word does not belong with the others?', choices: ['Sydney', 'Paris', 'Ottawa', 'Tokyo', 'Cairo'], explanation: 'Sydney is not a national capital (Canberra is). The others are capitals.' },
      { prompt: 'Which word does not belong with the others?', choices: ['Timid', 'Brave', 'Bold', 'Fearless', 'Valiant'], explanation: 'Timid means lacking courage. The others are synonyms for courageous.' },
    ],
  }),
  handSlot({
    id: 'verbal.vocabulary',
    section: 'verbal',
    difficulty: 3,
    title: 'Vocabulary',
    timeLimit: 25,
    quick: true,
    items: [
      { prompt: 'Which word is closest in meaning to LOQUACIOUS?', choices: ['talkative', 'quiet', 'clever', 'angry', 'bright'], explanation: 'Loquacious means tending to talk a great deal.' },
      { prompt: 'Which word is closest in meaning to BENEVOLENT?', choices: ['kind', 'wealthy', 'cheerful', 'wise', 'strict'], explanation: 'Benevolent means well-meaning and kindly.' },
      { prompt: 'Which word is closest in meaning to OBFUSCATE?', choices: ['confuse', 'clarify', 'destroy', 'delay', 'decorate'], explanation: 'To obfuscate is to make something unclear or confusing.' },
      { prompt: 'Which word is closest in meaning to GREGARIOUS?', choices: ['sociable', 'greedy', 'gigantic', 'stubborn', 'generous'], explanation: 'Gregarious means fond of company; sociable.' },
      { prompt: 'Which word is closest in meaning to EPHEMERAL?', choices: ['fleeting', 'eternal', 'airy', 'invisible', 'magical'], explanation: 'Ephemeral means lasting a very short time.' },
      { prompt: 'Which word is closest in meaning to CANDID?', choices: ['frank', 'sweet', 'hidden', 'careful', 'bright'], explanation: 'Candid means truthful and straightforward; frank.' },
    ],
  }),
  handSlot({
    id: 'verbal.anagram',
    section: 'verbal',
    difficulty: 3,
    title: 'Anagram',
    timeLimit: 45,
    mode: 'word',
    placeholder: 'Type the word',
    items: [
      { prompt: 'Rearrange the letters RAGNOE to spell a fruit.', accept: ['orange'], explanation: 'RAGNOE unscrambles to ORANGE.' },
      { prompt: 'Rearrange the letters PHANTELE to spell an animal.', accept: ['elephant'], explanation: 'PHANTELE unscrambles to ELEPHANT.' },
      { prompt: 'Rearrange the letters GOKANORA to spell an animal.', accept: ['kangaroo'], explanation: 'GOKANORA unscrambles to KANGAROO.' },
      { prompt: 'Rearrange the letters TAMINOUN to spell a landform.', accept: ['mountain'], explanation: 'TAMINOUN unscrambles to MOUNTAIN.' },
      { prompt: 'Rearrange the letters NETDIST to spell an occupation.', accept: ['dentist'], explanation: 'NETDIST unscrambles to DENTIST.' },
      { prompt: 'Rearrange the letters LAGORTUP to spell a country.', accept: ['portugal'], explanation: 'LAGORTUP unscrambles to PORTUGAL.' },
    ],
  }),
];
